name = "raceassist-router" 
main ="src/index.ts"
compatibility_date = "2022-05-03"

[[r2_buckets]]
binding = 'BUCKET_BET'
bucket_name = 'raceassist-bet'

[[r2_buckets]]
binding = 'BUCKET_RESULT'
bucket_name = 'raceassist-result'

[[r2_buckets]]
binding = 'BUCKET_HORSE'
bucket_name = 'raceassist-horse'
